import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
const inter = Inter({ subsets: ["latin"] });
import React from "react";
export const metadata: Metadata = {
  title: "Register Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div
        style={{
        //   border: "2px solid blue",
        //   height: "100%",
        //   display: "block",
        //   padding: "20px",
        //   textAlign: "center",
        //   backgroundImage: "url('/bg.png')",
        //   backgroundSize: "cover",
        //   backgroundRepeat: "no-repeat",
        //   backgroundAttachment: "fixed",
        }}
      >
        {children}
      </div>
    </>
  );
}